---
stages:
  - docker
  - acceptance

docker:
  stage: docker
  image: docker:stable
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    MONGO_URL: mongodb://angel_movo:ange1_movo@ds235711.mlab.com:35711/car_pooling
  services:
    - docker:dind
  before_script:
    - docker info
    - docker login -u ${CI_REGISTRY_USER} -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build . -t ${CI_REGISTRY_IMAGE}:latest
    - docker push ${CI_REGISTRY_IMAGE}:latest

acceptance:
  image: cabify/challenge:latest
  stage: acceptance
  only:
    - master
  variables:
    MONGO_URL: mongodb://angel_movo:ange1_movo@ds235711.mlab.com:35711/car_pooling
  services:
    - name: ${CI_REGISTRY_IMAGE}:latest
      alias: pooling
  script:
    - /harness --address http://pooling:9091 acceptance
