---
stages:
  - build
  - run
  - acceptance

build:
 stage: build
 script:
   - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
   - pip install docker-compose
   - docker-compose up -d
   - bin/build

run:
  stage: run
  script:
    - bin/run
    - bin/wait

# build_image:
#   stage: docker
#   image: docker:latest
#   variables:
#     DOCKER_HOST: tcp://docker:2375/
#    DOCKER_DRIVER: overlay2
#    DOCKER_TLS_CERTDIR: ""
#   services:
#     - docker:dind
#   script:
#     - echo As a helper here you have a sample of how to build and push a \
#     docker image to the provided gitlab registry.
#     - echo ${CI_JOB_TOKEN} | docker login --password-stdin -u ${CI_REGISTRY_USER} ${CI_REGISTRY}
#     - docker build . -t ${CI_REGISTRY_IMAGE}:latest
#     - docker push ${CI_REGISTRY_IMAGE}:latest

## Uncomment the acceptance step and do not remove or edit, this step is
## required for us to accept your submission!

acceptance:
  image: myolnir/car-pooling-challenge-myolnir
  stage: acceptance
  only:
    - master
  dependencies: []
  services:
    - name: myolnir/car-pooling-challenge-myolnir:latest
      alias: pooling
  script:
    - /harness --address http://pooling:9091 acceptance
