---
stages:
  - docker
  - acceptance


# build:
#   stage: build
#   image: # Add an image to build your service
#   artifacts:
#     paths:
#       - bin/
#   script:
#     - echo do something to build the binary or whatever

# build_image:
#   stage: docker
#   image: docker:latest
#   variables:
#     DOCKER_DRIVER: overlay2
#     DOCKER_TLS_CERTDIR: ""
#   services:
#     - docker:dind
#   script:
#     - echo As a helper here you have a sample of how to build and push a \
#     docker image to the provided gitlab registry.
#     - echo ${CI_JOB_TOKEN} | docker login --password-stdin -u ${CI_REGISTRY_USER} ${CI_REGISTRY}
#     - docker build . -t ${CI_REGISTRY_IMAGE}:latest
#     - docker push ${CI_REGISTRY_IMAGE}:latest

docker:
  stage: docker
  image: docker:stable
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:dind
  before_script:
    - docker info
    - docker login -u ${CI_REGISTRY_USER} -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build . -t ${CI_REGISTRY_IMAGE}:latest
    - docker push ${CI_REGISTRY_IMAGE}:latest

acceptance:
  image: cabify/challenge:latest
  stage: acceptance
  only:
    - master
  variables:
    MONGO_URL: mongodb://angel_movo:ange1_movo@ds235711.mlab.com:35711/car_pooling
  services:
    - name: ${CI_REGISTRY_IMAGE}:latest
      alias: pooling
  script:
    - docker login -u ${CI_REGISTRY_USER} -p $CI_JOB_TOKEN $CI_REGISTRY
    - /harness --address http://pooling:9091 acceptance
